### ISSUE TITLE
Alt aware mappability?

### ISSUE THREAD

**Issue by duartemolha** [cpockrandt/genmap#10]
Hi.

I have not started testing your software but have a question.

As I am sure you know human HRCh38 has a bunch of alt sequences where variations to some areas of the genome have been deposited.

These alt sequences usually are large and contain the same exact sequence as the main assembly on the flanking of the variation store

for example you can see this occurs on gene CLIC1.

where that sequence exists in the main chr6 assembly and also on 
chr6_GL000251v2_alt
chr6_GL000252v2_alt
chr6_GL000253v2_alt
chr6_GL000255v2_alt
chr6_GL000254v2_alt
chr6_GL000256v2_alt

When creating the index, the genomic regions on the main assembly that map perfectly to these alt sequences are then labeled as not unique even know biologicaly they are... but on input fasta file of the assembly has these artificial fragments included

Apart from creating a new index with these alt sequences removed, are there plans to support flagging these alt sequences so that the software discards them from the mappability analysis?

**Comment by duartemolha** [comment]
bwakit provides a list of the alt sequences in their resources folder ... it is used for alt aware aligment

**Comment by cpockrandt** [comment]
Hi @duartemolha,

flagging certain sequences from being counted would significantly slow down the computation of the mappability, since the hits not only have to be counted but also localized. I think this mostly affects the human genome and (re-)indexing it does not take too much resources, I don't think that we will implement such a feature in the near future.

Thanks for bringing this up, the indexed version of the human genome does indeed contain alt sequences which I will remove shortly.

**Comment by duartemolha** [comment]
Thanks... That is already a good action. Not only the alt sequences it
would also be good to use a reference that has the par regions on chrY
hardmasked as all PAR genes using the current reference are being assigned
0.5 mappability and this is obviously incorrect

**Comment by duartemolha** [comment]
In addition... Please use a reference that has the chromosomes using the
usual chr1...22, X and Y.

When using the index you provide and when you try to convert the wig output
file to big wig , it fails because it does not recognise the chromosomes.

**Comment by cpockrandt** [comment]
I re-indexed and uploaded the genomes and I will change the code for index creation (and bed files for selecting a subset). The indices don't contain alt sequences anymore, only chromosomes and unlocalized/unplaced scaffolds.

I did not mask the PAR regions. I understand your point but I think it might be a bit too specific. There might be other regions that are worth masking too for certain applications and for some applications one might even want to do gender-specific indices anyway (i.e., exclude the Y chromosome). It's probably best to build a custom index in these cases.

**Comment by duartemolha** [comment]
I am not sure I agree with you on par regions... By not masking it you are
saying there are 2 identical regions of mappability on regular par regions.
But this is not the case. Those regions exist on the genome exactly one
time wether you are male of female.... The same as every other region on
autosomal chromosomes ...that is in fact why it is called pseudoautossomal.

By not masking it and saying the mappability there is 0.5 the this would be
true of every other chromosome.

Moreover regions that do indeed have lower mappability on par regions are
now going to have the wrong value.

But the tool is not mine and I will differ that decision to you.
