### ISSUE TITLE
-d or --cvs no output

### ISSUE THREAD

**Issue by duartemolha** [cpockrandt/genmap#11]
Hi

I was very happy to find a option to give me all the genomic locations is the Kmers

I basicaly wanted to use it to find all the genomic locations of 50 bp kmers on a specific region of the genome

so I used this command:

`genmap map -K 50 -E 5 -I my index -O my_orf_map --selection myBed.bed -d
`
However I did not get any output
myBed:
`chrX    38284365        38288084        ORF15`

Am I missing something?

Thanks

Duate

**Comment by cpockrandt** [comment]
Is it maybe related to #12?

GenMap expects the identifiers to match exactly at the moment. It's already on my todo-list and I will push a commit hopefully by the end of the week!

**Comment by duartemolha** [comment]
AH ... thanks
