### ISSUE TITLE
better explanation of cvs output

### ISSUE THREAD

**Issue by duartemolha** [cpockrandt/genmap#15]
I was trying to find in the help documentation , but failed to do so.

Can you please explain the output of the CSV file when using -d option?

Thanks

Duarte

**Comment by duartemolha** [comment]
the region I ask this is because some of one of the lines I got was this:
22,38285985;0,166400969|22,38285985
22,38286465;9,129780021|9,129780042|9,129780063|9,129780084|9,129780105|9,129780126|22,38286444|22,38286465

what does this mean exactly?

**Comment by cpockrandt** [comment]
Good point! I added a section to the [wiki](https://github.com/cpockrandt/genmap/wiki#csv-format-for-detailed-mappability-information) explaning the csv format.

Feel free to reopen the issue if there are any questions left!

**Comment by duartemolha** [comment]
Would it be possible to use the name of the sequence from the fasta file instead of it's number?

It would be much helpful if it said chr1 instead of 0 and chr2 instead of 1 , etc...

for the example I gave above I am assuming :
this:
22,38285985;0,166400969|22,38285985

corresponds to the 23rd sequence in the indexed fasta file (chrX)

so chrX,38285985;chr1,166400969|chrX,38285985

correct?

**Comment by cpockrandt** [comment]
Unfortunately that would bloat up the csv file even more. If you still have the fasta file laying around, you can just replace it with a one-liner in awk

    awk 'BEGIN{id = 0} FNR==NR{ if ($0 ~ /^>/) { gsub(/>/, "", $0); f[id++] = $0; } next; } { for (i in f) { pattern = "((^)|(;)|(|))" i ","; $0 = gensub(pattern, "\\1" f[i] ",", "g"); } print $0 }' genome.fa genome.genmap.csv > new.csv

**Comment by duartemolha** [comment]
Ok.. thanks... That is pretty much what I had done :)
