### ISSUE TITLE
k(4,1)-mappability for readme example

### ISSUE THREAD

**Issue by alexandervogel** [cpockrandt/genmap#16]
Hi, I understood the mappability to be the reciprocal value of how often a k-mer given e errors occurs in T. Looking into the provided example in the README of the k(4,1)-mappability for T = ATCTAGGCTAATCTA I can't follow how M[i] is calculated given the F[i] frequencies. Running genmap with k=4 and E=1 gave me the following mappability scores: 0.5 0.333333 0.5 1 1 1 0.333333 0.5 1 1 0.5 0.333333 0 0 0 that make sense for the given F[i].
Would be grateful to figure out where my mistake is.
Thanks

**Comment by cpockrandt** [comment]
Hi,

thanks for pointing that out! Not sure what went wrong there, but the mappability values are indeed incorrect. I fixed it in the README.
