### ISSUE TITLE
conda installation fails

### ISSUE THREAD

**Issue by lsantuari** [cpockrandt/genmap#17]
I am trying to install genmap `v1.2.0` on `osx-64`  with `conda 4.8.3` but I am getting an `UnsatisfiableError`. Could you please see if it works for you in case you have access to a `osx-64` system?

**Comment by cpockrandt** [comment]
Thanks for reporting it! I am able to reproduce the error on osx with a clean installation of Anaconda (it seems to work on Linux without any issues):

```
UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package libcxx conflicts for:
genmap -> libcxx[version='>=4.0.1']
python=3.7 -> libcxx[version='>=4.0.1']
```

I don't see any conflicts here with libcxx, version 4.0.1 is already installed on my system. I have a hunch that it might be related to ``llvm-openmp``. I will continue to look into this!

**Comment by lsantuari** [comment]
@cpockrandt Thank you for looking into this. I will use the Linux version for the time being.

**Comment by cpockrandt** [comment]
@lsantuari Can you try it again? It works now for me (still printing a few `failed with initial frozen solve. Retrying with flexible solve`, but it eventually installs GenMap)

**Comment by lsantuari** [comment]
It works now. Thank you again for the support.
