### ISSUE TITLE
ERROR: Malformed index.info file! Could not find key 'alphabet_size'.

### ISSUE THREAD

**Issue by fuesseler** [cpockrandt/genmap#22]
Hi!
I was able to produce an index for my genome using the following commands on SLURM:

```
export TMPDIR=/mnt/n-hpc-cz1/raid60/flora/
genmap index -F ../ref_normalized.fasta -I ./genmap-index -A skew
```
but when I try to run genmap on it with the code below, i get an Error as seen below:

```
INDEX=mnt/n-hpc-cz1/raid60/flora/genmap-workdir/ref_genmapindex
genmap map -K 100 -E 2 -I $INDEX -O ./genmap-output --txt --csv --threads 20 --memory-mapping

################################################################################
### Output:
################################################################################
ERROR: Malformed index.info file! Could not find key 'alphabet_size'.
```
In the Indexing, the following 21 files were created:
index.ids.concat   index.info.limits  index.lf.drs      index.lf.pst          index.rev.lf.drs      index.rev.lf.pst  index.sa.val
index.ids.limits   index.lf.drp       index.lf.drv      index.rev.lf.drp      index.rev.lf.drv      index.sa.ind      index.txt.concat
index.info.concat  index.lf.drp.sbl   index.lf.drv.sbl  index.rev.lf.drp.sbl  index.rev.lf.drv.sbl  index.sa.len      index.txt.limits

I repeated the indexing once, but still got the same error...
Do you have any idea what could be the issue?

My best,
Flora

**Comment by cpockrandt** [comment]
Hi Flora,

I could not reproduce the error with the latest version from the GitHub repository. It sounds like the index was built with a different version than the mapping is performed, or there is a bug in an older genmap version.

Can you tell me the version of genmap you used (and where you got it, i.e., bioconda, a release from GitHub or did you build the source yourself)? Also sharing the files `index.info.concat` and `index.info.limits` could help tracking down the error (these files only have a few bytes). Can you upload them or send them to me via e-mail (c.p [ät] fu-berlin . de )?

Thank you!

**Comment by fuesseler** [comment]
Hi Christopher,

I used the bioconda version. The help function reports it as version 1.2.0, last update  Feb 21 2020. I sent you the 2 files per Email just now.

Thank you for your help!

**Comment by cpockrandt** [comment]
I figured it out, and I must admit the error message is really confusing. I think the path to the index is incorrect, so what genmap is telling you, that it cannot find the index 😬

If I had to guess, I think you are missing a slash at the very beginning (before `mnt`):

`INDEX=/mnt/n-hpc-cz1/raid60/flora/genmap-workdir/ref_genmapindex`

**Comment by fuesseler** [comment]
Hi,
Yep, that seems to have been the problem! The error message disappeared.
Thanks for catching it, typos are my bane of existence..
Now I only need to figure out how much memory I need to supply, because
SLURM keeps killing the process due to being out of memory.
My index is ~ 7GB .. do you have any tips how much memory is generally
needed? I tried the memory mapping option too, but that also got killed
with the same message.

My best,
Flora

Am So., 12. Sept. 2021 um 21:40 Uhr schrieb cpockrandt <
***@***.***>:

**Comment by cpockrandt** [comment]
You need enough space to load the index into memory + `4n` bytes for a genome of length `n`. Since you are on a system with SLURM and not on a personal computer, I guess you should have enough RAM available to add a few extra GB (just to be safe). I would avoid using ``--memory-mapping`` if you can. Depending on your system, it can make it a lot slower, and GenMap does not require an excessive amount of RAM, so that most people actually don't need it.

**Comment by fuesseler** [comment]
It works fine now, thanks for the tips and support!

Best,
Flora

Am Mo., 13. Sept. 2021 um 09:35 Uhr schrieb cpockrandt <
***@***.***>:
