### ISSUE TITLE
GenMap getting stuck indexing?

### ISSUE THREAD

**Issue by joshuak94** [cpockrandt/genmap#6]
Hey Chris,

I'm trying to index the mm9 genome (ftp://ftp.ensembl.org/pub/release-67/fasta/mus_musculus/dna/), with the following options: RAM 8 Gb, secondary memory 64 Gb, 8 cores, Skew algorithm. For some reason, the program seems to be getting stuck fairly early on into the program. My index folder has the following files:
```
-rw-r--r-- 1 joshjayk group  23K May 29 21:24 index.ids.concat
-rw-r--r-- 1 joshjayk group 1.7K May 29 21:24 index.ids.limits
-rw-r--r-- 1 joshjayk group  107 May 29 21:24 index.info.concat
-rw-r--r-- 1 joshjayk group   56 May 29 21:24 index.info.limits
```

The size of the files hasn't changed in a while.

Any thoughts as to why this is happening?

**Comment by cpockrandt** [comment]
The files you see there are written to disk immediately after scanning over the input data. The remaining files (for the index) will be written at the very end of the indexing procedure, i.e., it will take some time until you see any "progress" on disk. Maybe I should write it all to disk in the end to avoid this confusion.

Indexing of the mouse genome with Skew might take a few hours (depending on the hardware).

**Comment by joshuak94** [comment]
Ahhhh makes sense. Thanks! Hope you enjoy your time at Johns Hopkins :)
