### ISSUE TITLE
bed output not zero based

### ISSUE THREAD

**Issue by cruckert** [cpockrandt/genmap#8]
When running genmap with -b option the output bed file contains lines like

1	17222	17222	-	0.333333
1	35758	35758	-	0.25

As in bed format start coordinates ares 0-based and end coordinates are 1-based even one bp intervals are represented by differing start and end coordinates, e.g.

1    17222   17223  G

**Comment by cpockrandt** [comment]
Thanks for reporting this bug! I accidentally used closed-intervals for bed-files. I already fixed the code and will upload new binaries later today!

**Comment by cpockrandt** [comment]
Binaries are now also released.
