### ISSUE TITLE
Index genome size limit?

### ISSUE THREAD

**Issue by speromelior** [cpockrandt/genmap#9]
Thanks first for the link here from gem3-mapper.  I am working on a large gene family in wheat and mappability is a key metric for evaluating the limits of what can be mapped stringently. 

I have a Conda install that works fine on fungal genomes (Zymoseptoria tritici) and for wheat chromosome 1A, but fails trying to index the entire wheat assembly (https://plants.ensembl.org/Triticum_aestivum/Info/Index).  This is a problem since the mappability metric is only meaningful in the context of an intact genome.  It comes out as a write error in the SeqAn library

The command is:
genmap index -F  Triticum_aestivum.IWGSC.dna.toplevel.fa  -I taestivumIWGSCGenMapIndex
stdout:
"The index will now be built. This can take some time (e.g., 2-3 hours with Skew7 for the human genome).
Create fwd Index ..."

The initial files are generated:
index.ids.concat 2.3K
index.ids.limits 184
index.info.concat 107
index.info.limits 56
Followed by the error:
"Asynchronous I/O operation failed (waitFor): "Bad file descriptor"
fildes:  3
buffer:  7f0b39c37000
offset:  15ba000000
nbytes:  2000000
event:   1
Raddr:   0x7f0b48626308
/opt/conda/conda-bld/genmap_1574097877469/work/include/seqan/include/seqan/file/file_page.h:816 FAILED!  (WRITING operation could not be completed: "Bad file descriptor")

stack trace:
  0    [0x7f0b46cd8a09]  genmap(+0x232a09)
  1    [0x7f0b46b6842c]  genmap(+0xc242c)
  2    [0x7f0b46f88e9e]  genmap(+0x4e2e9e)
  3    [0x7f0b46f9474e]  genmap(+0x4ee74e)
  4    [0x7f0b46bcbb8d]  genmap(+0x125b8d)
  5    [0x7f0b46d0c1a9]  genmap(+0x2661a9)
  6    [0x7f0b46e04ac1]  genmap(+0x35eac1)
  7    [0x7f0b46b1ef6b]  genmap(+0x78f6b)
  8    [0x7f0b46cf33c6]  indexMain(int, char const**) + 0x5706
  9    [0x7f0b46b759dc]  main + 0x1cc
 10    [0x7f0b4650dd1d]  __libc_start_main + 0xfd
 11    [0x7f0b46b75f1b]  genmap(+0xcff1b)

Aborted"

**Comment by cpockrandt** [comment]
Hi @speromelior,

thanks for trying out GenMap! Indexing genomes unfortunately still takes a lot of resources (secondary memory) with GenMap, at the moment roughly 20x the size of the genome you want to index. Your error message indicates that you are running out of space/quota. You can try using a different directory/disc with more space/quota:

    $ export TMPDIR=/somewhere/else/with/more/space

If you don't have the resources for indexing, I can upload the indexed wheat genome for you to download.

**Comment by cpockrandt** [comment]
I created and uploaded the wheat index (rel 45) and added it to the list of pre-built indices in the README. Feel free to open another issue if you have any other questions.

http://ftp.imp.fu-berlin.de/pub/cpockrandt/genmap/indices/triticum_aestivum-dna5.tar.gz

**Comment by speromelior** [comment]
That's great, thank you very much for generating an index for us. I did get an index locally. I don't know how long it took, it was still running on Friday after a day and a half and generated ~600Gb of temporary files (the 20x estimate may be conservative for large genomes).  The index folder I have is 69Gb, did you use a masked reference?

**Comment by cpockrandt** [comment]
I used the unmasked genome [1]. Did you run the indexing with a lower sampling value (`--sampling` / `-S`)? This would increase the file size of `index.sa.val` but will not affect the mappability results.

If this is not the case and you can upload your index somewhere, I can further look into it!

[1] ftp://ftp.ensemblgenomes.org/pub/plants/release-45/fasta/triticum_aestivum/dna/Triticum_aestivum.IWGSC.dna.toplevel.fa.gz
